name: Chrome

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - uses: papeloto/action-zip@v1
        with:
          files: dist/ manifest.json
          dest: zipped.zip

      - name: Upload Extension
        run: bunx chrome-webstore-upload-cli upload --source zipped.zip --extension-id anbclhoojgdmafmimakfpmklcpnbibhg --client-id ${{ secrets.CLIENT_ID }} --refresh-token ${{ secrets.REFRESH_TOKEN }} --auto-publish --trusted-testers
