name: "Release"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
            node-version: '16'

      - name: Install Dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
      
      - name: Copy manifest to build folder
        run: cp ./manifest.json ./dist/
      
      - name: Zip It
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: zipped.zip
      
      - name: Build chrome version
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'zipped.zip'
          crxFilePath: 'out/startpage.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }},
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: StartPage Chrome
          path: out/*.crx

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./dist

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          apiUrlPrefix: https://addons.mozilla.org/api/v4 

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}
